# Project information
site_name: 'BigGIS Documentation'
site_description: 'Central documentation of the BigGIS project'
site_author: 'BigGIS Team'

# You can set the 'site_url' parameter explicitly, otherwise it points to the documentation root
#site_url: 'http://biggis-project.eu/biggis-docs'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/biggis-project/biggis-docs'

# You can disable edit icon for pages by setting edit_uri:"", otherwise it points to github
#edit_uri: ""


# Copyright
copyright: '<a href="https://www.fzi.de/footer/impressum/">Impressum: FZI Forschungszentrum Informatik am Karlsruher
Institut f√ºr Technologie.</a>'

#copyright: 'Copyright &copy; 2017 - 2021 SeRoNet Project'

# Documentation and theme
theme:
  name: material
  favicon: 'favicon.ico' # this icon appears in the browser's tab
  logo: 'favicon.svg' # this icon appears in the top left corner on each page
  palette:
    primary: 'dark blue'
    accent: 'blue'
  feature:
      tabs: true

extra:
  social: # see http://fontawesome.io/icons/ for allowed 'type' values
      - type: 'globe'
        link: 'http://biggis-project.eu'
      - type: 'github'
        link: 'https://github.com/biggis-project'

# Extensions
markdown_extensions:
  - footnotes:                  # https://squidfunk.github.io/mkdocs-material/extensions/footnotes/
  - admonition:                 # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - pymdownx.arithmatex:        # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#arithmatex-mathjax
  - pymdownx.smartsymbols:      # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#smartsymbols
  - pymdownx.superfences:       # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - pymdownx.magiclink:         # https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
      repo_url_shortener: true
  - codehilite:                 # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
      guess_lang: false
  - toc:
      permalink: true

extra_javascript:
  - 'extra.js'

pages: # Generated using ./fix-mkdocs-pages.sh on Mon Nov 27 22:24:33 CET 2017
    - About BigGIS: ./index.md
    - Architecture:
        - Overview: ./architecture/index.md
        - Components: ./architecture/Docker_Containers.md
        - bwCloud: ./architecture/Infrastructure_on_bwCloud.md
        - StreamPipes: ./architecture/StreamPipes.md
    - Contributing: ./contributing.md
    - Data sources:
        - Datasets in BigGIS: ./data-sources/index.md
        - Weather stations: ./data-sources/weather-stations.md
    - Demos:
        - About demos ...: ./demos/index.md
        - EnviroCar (Smart City): ./demos/enviro-car.md
        - Gas Cloud Detection: ./demos/gas-detect.md
        - Gas Cloud Prediction: ./demos/gas-predict.md
        - Heatstress Routing App: ./demos/heatstress.md
        - Hotspot analysis demo: ./demos/hotspots.md
        - Invasive species: ./demos/invasive-spec.md
        - Landuse classification: ./demos/landuse.md
        - Optimal flight plan for drones: ./demos/optimize-drones.md
        - Placement of sensors under uncertainty: ./demos/optimize-sensors.md
        - Stability of hotspots: ./demos/Stability_of_hotspots.md
        - Urban Heat Islands: ./demos/urban-heat-islands.md
    - Documentation Howto: ./docs-howto.md
    - Scenarios:
        - Smart City: ./scenarios/01_city.md
        - Disaster Management: ./scenarios/02_bos.md
        - Environment: ./scenarios/03_env.md
